spring.application.name=booking-service
api.prefix=/booking-service/v1
server.servlet.context-path=${api.prefix}

# PostgreSQL datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booking_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never

# Spring profiles
spring.profiles.group.dev=dev,common
spring.profiles.group.qa=qa,common
spring.profiles.group.prod=prod,common

integration.payment.base-url=${INTEGRATION_PAYMENT_BASE_URL:http://localhost:8084}
integration.payment.internal-shared-secret=${INTEGRATION_PAYMENT_INTERNAL_SHARED_SECRET:dev-shared-secret-change-me}
integration.seats-allocation.base-url=${INTEGRATION_SEATS_BASE_URL:http://localhost:8083/seats-allocation-service/v1}
integration.seats-allocation.service-name=${INTEGRATION_SEATS_SERVICE_NAME:booking-service}
integration.seats-allocation.service-token=${INTEGRATION_SEATS_SERVICE_TOKEN:booking-service-dev-token}
